### ISSUE TITLE
Панель управления

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD4thTask#10]
Нужно добавить валидацию значении в форме, чтобы было нельзя всё сломать, к примеру, введя максимальное значение меньше минимального или задав 200 ползунков

**Comment by rsilivestr** [comment]
>Нужно добавить валидацию значении в форме

Добавил валидацию значений в модели (принимает либо один, либо все 4 параметра, т. к. все друг от друга зависят): 43ebbfe

**Comment by Fr0stmourne** [comment]
Не до конца корректно работает еще

![image](https://user-images.githubusercontent.com/46089168/104887618-a4c32000-597c-11eb-8386-1dd9dd674ba5.png)

**Comment by rsilivestr** [comment]
4c210aa2ebfbd3232e88808b6cdb126815216a56

**Comment by Fr0stmourne** [comment]
Отрицательные значения все еще справа от нуля, как будто там минусов нет вообще. И в самой панели не должно отображаться минимальное 0 и максимальное -100, в этом же нет смысла. Можно их менять местами, как вариант

![image](https://user-images.githubusercontent.com/46089168/105007200-bbcf4400-5a48-11eb-9e72-2dbb7d8bb79e.png)

**Comment by rsilivestr** [comment]
>Отрицательные значения все еще справа от нуля, как будто там минусов нет вообще. И в самой панели не должно отображаться минимальное 0 и максимальное -100, в этом же нет смысла. Можно их менять местами, как вариант

Добавил в настройки слайдера опцию allowReversedValues в 887d6a9, которая разрешает выставлять минимальное значение больше максимального, которая по умолчанию отключена.
