### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by AkhmadBabaev** [rsilivestr/FSD4thTask#15]
![изображение](https://user-images.githubusercontent.com/51095975/112694442-6c1b5780-8e93-11eb-9b2f-0c04ebd1c765.png)

У label должен быть курсор pointer, а так же работает нажатие на пустое пространство с право от полей и чекбоксов.

**Comment by AkhmadBabaev** [comment]
![demo](https://user-images.githubusercontent.com/51095975/112694765-f95eac00-8e93-11eb-8e30-c1d0702b4cc1.gif)

Некорректное поведение.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/112695022-6c682280-8e94-11eb-926d-a572aa6b8ef3.png)

Значение 97 не валидное, там точки 96 99 100.

**Comment by rsilivestr** [comment]
> Некорректное поведение.

В чем именно?

**Comment by AkhmadBabaev** [comment]
> В чем именно?

Двигаю один бегунок смешается и другой. Обычно делают так чтобы один бегунок не мог зайти за другой, либо для большего удобства один бегунок может зайти за другой, но никаких смещений одновременно двух бегунков не происходит.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/113359764-26f29c00-9351-11eb-9314-95099e20f700.png)

Из такого положения не получается перетащить левый бегунок.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/113360137-dc255400-9351-11eb-9c01-d65b082a77c3.png)

Сильно расходятся позиции точек шкалы с позициями ползунков.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/113360250-10991000-9352-11eb-9d35-ca03b6f07e07.png)

Сделал горизонтальным левый слайдер.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/114106999-b7445a00-98d8-11eb-940f-d1fbd2eecbda.png)

При изменении направления слайдера ползунок оказывается позади трека.
