### ISSUE TITLE
Размытый контракт

### ISSUE THREAD

**Issue by prodderman** [rsilivestr/FSD4thTask#20]
Пока заметил только в Модели. 

Во-первых, в `TModelOptions` есть index signature (Его роль не понятна), а остальные настройки опциональны. Как другой программист, посмотрев на тип, я ожидаю увидеть четкий контракт (ограниченный набор настроек) слайдера. Сейчас же не понятно какие еще могут быть настройки и почему. 

Во-вторых, Некоторые функциях такие как `setValue`, `configure` имеют неочевидный контракт: По типам в функции попадают вполне конкретные значения, но почему то присутствуют излишние проверки. Например `value` в типом `number` проверяется на `number`. Это следствие того, что в модель попадают "грязные" невалидные значения 

Модель ответственна за расчеты. Она определяет свой контракт, а код, использующий модель, должен этот контракт удовлетворить (передать конкретные валидные значения). Таким образом другие программисты испытают меньшую когнитивную нагрузку при чтении кода модели, потому что в ней будет сконцентрирована только бизнес-логика

P.S. Не валидные значения - я имею в виду неопределенного типа, которые пришли от юзера. Которые по-сути типа `unknow`. То есть проверки по типу "значение слайдера больше максимального или меньше минимального" это часть бизнес логики и должны быть в модели

**Comment by rsilivestr** [comment]
> четкий контракт

Сделал все настройки `TModelOptions` обязательными, добавил `TModelOptionsPartial` для возможности передачи в `Model.setConfig` частичного объекта конфигурации. То же самое для `TViewOptions` и `TSliderOptions`.

> присутствуют излишние проверки

Убрал по возможности.
- Проверку на `NaN` из `Model.setValue` перенес в фасад (`Slider.setValue`).
- Логику `configure` изменил и перенёс в `setConfig`.

**Comment by prodderman** [comment]
>  добавил TModelOptionsPartial для возможности передачи в Model.setConfig частичного объекта конфигурации.

Для таких случаев есть Utility type Partial, поэтому там где нужно передавать частичную конфигурацию нужно делать примерно так:

`setConfig(config: Partial<TModelOptions>): void;`

**Comment by rsilivestr** [comment]
> Для таких случаев есть Utility type Partial

Круто. Спасибо за наводку, сейчас исправлю.

**Comment by rsilivestr** [comment]
@prodderman какие-то ещё замечания по исправлениям?
