### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD4thTask#3]
Контроллер взаимодейсвует напрямую с DOM, навешивая обработчик, такого быть не должно. По идее вьюха должна обрабатывать события сама и оповещать тех, кто следит за ее обновлениями, о новом результате
![image](https://user-images.githubusercontent.com/46089168/101928664-ee368780-3be6-11eb-863f-bf9fddd193ea.png)

**Comment by Fr0stmourne** [comment]
Никакой бизнес-логики по вычислению значений в контроллере тоже не должно быть
![image](https://user-images.githubusercontent.com/46089168/101929016-5c7b4a00-3be7-11eb-83e1-d4107968671a.png)

**Comment by Fr0stmourne** [comment]
А зачем тестовой панели знать про то, как внутри устроен слайдер? Она должна взаимодействовать с инстансом слайдера как с фасадом, дергая методы обновления, а уж что он из модели и вьюхи состоит, панели знать точно не обязательно
![image](https://user-images.githubusercontent.com/46089168/101929667-373b0b80-3be8-11eb-837d-0b312f36e29a.png)

**Comment by Fr0stmourne** [comment]
Шкала - это составная часть вью, ей совсем незачем получать сам инстанс, достаточно только списка необходимых опций, которые ей нужны для отрисовки, и тем более инстанс модели ей тоже ни к чему
![image](https://user-images.githubusercontent.com/46089168/101929949-8d0fb380-3be8-11eb-90a1-3adee23aa7ff.png)

**Comment by rsilivestr** [comment]
> Контроллер взаимодейсвует напрямую с DOM, навешивая обработчик, такого быть не должно. По идее вьюха должна обрабатывать события сама и оповещать тех, кто следит за ее обновлениями, о новом результате
> ![image](https://user-images.githubusercontent.com/46089168/101928664-ee368780-3be6-11eb-863f-bf9fddd193ea.png)

Я так понял, что за события в MVC отвечает контроллер. Если события повесить на view от контроллера ничего не останется. Его вообще убрать тогда?

**Comment by Fr0stmourne** [comment]
> > Контроллер взаимодейсвует напрямую с DOM, навешивая обработчик, такого быть не должно. По идее вьюха должна обрабатывать события сама и оповещать тех, кто следит за ее обновлениями, о новом результате
> > ![image](https://user-images.githubusercontent.com/46089168/101928664-ee368780-3be6-11eb-863f-bf9fddd193ea.png)
> 
> Я так понял, что за события в MVC отвечает контроллер. Если события повесить на view от контроллера ничего не останется. Его вообще убрать тогда?

Контроллер связывает модель и вьюху, без него они в идеале не должны знать о существовании друг друга, поэтому без него просто работать ничего не должно по идее, он как раз и дергает модель при изменении вьюхи и наоборот

**Comment by rsilivestr** [comment]
> Никакой бизнес-логики по вычислению значений в контроллере тоже не должно быть
> ![image](https://user-images.githubusercontent.com/46089168/101929016-5c7b4a00-3be7-11eb-83e1-d4107968671a.png)

Никакой бизнес-логики и нет, тут вычисляется относительная координата бегунка в % от длины слайдера. Модель же не знает ничего о геометрии слайдера. Координата относительно страницы ей ничего не скажет.

**Comment by Fr0stmourne** [comment]
> > Никакой бизнес-логики по вычислению значений в контроллере тоже не должно быть
> > ![image](https://user-images.githubusercontent.com/46089168/101929016-5c7b4a00-3be7-11eb-83e1-d4107968671a.png)
> 
> Никакой бизнес-логики и нет, тут вычисляется относительная координата бегунка в % от длины слайдера. Модель же не знает ничего о геометрии слайдера. Координата относительно страницы ей ничего не скажет.

Какой длины слайдер - дело только вьюхи и никого больше, в контроллере этого быть не должно)

**Comment by rsilivestr** [comment]
>Контроллер связывает модель и вьюху, без него они в идеале не должны знать о существовании друг друга, поэтому без него просто работать ничего не должно по идее, он как раз и дергает модель при изменении вьюхи и наоборот

Тогда это не MVC, а MVP, насколько я понимаю. Или скорее даже [MVA](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93adapter).

**Comment by Fr0stmourne** [comment]
> > Контроллер связывает модель и вьюху, без него они в идеале не должны знать о существовании друг друга, поэтому без него просто работать ничего не должно по идее, он как раз и дергает модель при изменении вьюхи и наоборот
> 
> Тогда это не MVC, а MVP, насколько я понимаю. Или скорее даже [MVA](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93adapter).

Да, это скорее ближе к MVP, но на риззоме и просят подобие MVP с пассивной вьхой

**Comment by rsilivestr** [comment]
> > > Контроллер связывает модель и вьюху, без него они в идеале не должны знать о существовании друг друга, поэтому без него просто работать ничего не должно по идее, он как раз и дергает модель при изменении вьюхи и наоборот
> > 
> > 
> > Тогда это не MVC, а MVP, насколько я понимаю. Или скорее даже [MVA](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93adapter).
> 
> Да, это скорее ближе к MVP, но на риззоме и просят подобие MVP с пассивной вьхой

Окей, пусть будет MVP.
А обязательно jQuery подключать? Толку от этой обертки 0. С удовольствием бы убрал.

**Comment by Fr0stmourne** [comment]
Да, обязательно, в этом в том числе задание состоит

**Comment by rsilivestr** [comment]
> Да, обязательно, в этом в том числе задание состоит

Ветка [jq](https://github.com/rsilivestr/FSD4thTask/tree/jq)

**Comment by Fr0stmourne** [comment]
Медиатор - всё же немного не то:
- у модели и вьюхи не должно быть инстанса презентера (зачем он им?)
- вью не должен подписываться напрямую на модель
Вообще реализация обсервера немного странная, observer в addObserver - это по сути функция, которая выполняется при наступлении события какого-то, в чем задумка весь вью добавлять как observer?
![image](https://user-images.githubusercontent.com/46089168/102795142-7540e800-43bd-11eb-9c07-1c3682c83599.png)

**Comment by Fr0stmourne** [comment]
И еще вот по этому методу вопрос, coord это какая величина здесь?
![image](https://user-images.githubusercontent.com/46089168/102798574-5d1f9780-43c2-11eb-90c8-c7c6abc7ef19.png)

**Comment by rsilivestr** [comment]
>у модели и вьюхи не должно быть инстанса презентера (зачем он им?)

Из модели уже убрал. А вью как будет обращаться к модели, через презентер, если у него ничего нет? Ни к модели не может обратиться, ни к презентеру? Или презентер должен наблюдать и за view, и за model? А что со шкалой и панелью управления? Модель отлично подходит для того, чтобы все на нее подписывались напрямую.

>вью не должен подписываться напрямую на модель

А как иначе?

>observer в addObserver - это по сути функция, которая выполняется при наступлении события какого-то, в чем задумка весь вью добавлять как observer

Понял, эврика)

>И еще вот по этому методу вопрос, coord это какая величина здесь?

Координата в процентах от длины слайдера.

**Comment by Fr0stmourne** [comment]
Почему модель реализует интерфейс обсервера, а у вью просто есть метод `notifyPresenter`? Это не очень хорошо, у него может быть только 1 подписчик. Лучше вью тоже унаследовать от обсервера.

**Comment by Fr0stmourne** [comment]
В компоненте шкалы что-то не очень понятное происходит, вот тут шкала ищет слайдер на странице и встраивается сама в него? Так не пойдет, собирать все компоненты вместе должен главный вью-компонент
![image](https://user-images.githubusercontent.com/46089168/103306604-00098e80-4a1f-11eb-9f67-aa7aaa08f557.png)

**Comment by Fr0stmourne** [comment]
Панель не является компонентом слайдера, она нужна только для демонстрации, должна быть вне его и взаимодействовать с ним через апи

**Comment by rsilivestr** [comment]
> Почему модель реализует интерфейс обсервера, а у вью просто есть метод `notifyPresenter`? Это не очень хорошо, у него может быть только 1 подписчик. Лучше вью тоже унаследовать от обсервера.


> В компоненте шкалы что-то не очень понятное происходит, вот тут шкала ищет слайдер на странице и встраивается сама в него? Так не пойдет, собирать все компоненты вместе должен главный вью-компонент

2dada352f6d5481e9c3d68c4924ef0e917687380

**Comment by rsilivestr** [comment]
>Панель не является компонентом слайдера

f60cc4dd305cf198309ff8cf58e46a7322c26b77 или нужно её отдельным плагином сделать?

**Comment by Fr0stmourne** [comment]
> > Панель не является компонентом слайдера
> 
> [f60cc4d](https://github.com/rsilivestr/FSD4thTask/commit/f60cc4dd305cf198309ff8cf58e46a7322c26b77) или нужно её отдельным плагином сделать?

Не совсем так, основная идея в том, что панель не знает о внутреннем устройстве слайдера и взаимодействует с методами его АПИ как с фасадом, поэтому подписок на модель в панели быть не должно. Это должна быть отдельная сущность (класс) вне плагина

**Comment by Fr0stmourne** [comment]
На демо-странице панели я не обнаружил, поэтому решил уточнить, что рядом со слайдером должна быть форма, где можно можно менять любые настройки слайдера, при этом он будет синхронно обновляться с этой формой

**Comment by rsilivestr** [comment]
>подписок на модель в панели быть не должно

5c01a45

> форма, где можно можно менять любые настройки слайдера

c637575

**Comment by Fr0stmourne** [comment]
Еще вопрос по подпискам: почему `notifyObservers` реализуется отдельно в модели и вью? Лучше реализовать его в классе обсервера

**Comment by Fr0stmourne** [comment]
> > форма, где можно можно менять любые настройки слайдера
> 
> [c637575](https://github.com/rsilivestr/FSD4thTask/commit/c637575c97d1582778a38cd04becff844e7b3cf8)

Было бы здорово еще добавить переключение между режимами с 1 и 2 бегунками

**Comment by rsilivestr** [comment]
>добавить переключение между режимами с 1 и 2 бегунками

5a17ad6

**Comment by rsilivestr** [comment]
>реализовать `notifyObservers` в классе обсервера

eb1d0c5

**Comment by Fr0stmourne** [comment]
А по какому принципу сделано разделение, что у большинства сущностей есть свой компонент, а у трека и прогресса нет и они создаются в методах основного вью?

**Comment by rsilivestr** [comment]
>А по какому принципу сделано разделение, что у большинства сущностей есть свой компонент, а у трека и прогресса нет и они создаются в методах основного вью?

8164705
f6ded48
