### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD4thTask#4]
Обычно JQuery плагины всё же инициализируются сразу вызовом метода без вспомогательного объекта, так будет привычнее при использовании
```
$('#slider').slider(...)
```

**Comment by Fr0stmourne** [comment]
Необходимо добавить методы для обновления значения (а лучше вообще любых настроек) на лету
![image](https://user-images.githubusercontent.com/46089168/101930691-8a618e00-3be9-11eb-9930-e6d02b5c5653.png)

**Comment by rsilivestr** [comment]
> Обычно JQuery плагины всё же инициализируются сразу вызовом метода без вспомогательного объекта, так будет привычнее при использовании
> 
> ```
> $('#slider').slider(...)
> ```

Сделал в ветке jq

>Необходимо добавить методы для обновления значения (а лучше вообще любых настроек) на лету

Сделал. Добавил описание в README

**Comment by Fr0stmourne** [comment]
Нужно добавить возможность установки дефолтных значений

**Comment by rsilivestr** [comment]
> Нужно добавить возможность установки дефолтных значений

e2a38c4b295f744ee346a35e32f58a7a2abb9338, b872403626ae8bf34f36cbd350bc76d9d8ac99ae

**Comment by Fr0stmourne** [comment]
Теперь нужно завернуть всё в jquery-обертку, совместив ветки `mvp` и `jq`

**Comment by rsilivestr** [comment]
>завернуть всё в jquery-обертку

e33dc13

**Comment by Fr0stmourne** [comment]
Появилась ошибка ts'a, нужно поправить
![image](https://user-images.githubusercontent.com/46089168/104477878-aedacc80-55d2-11eb-9241-7ea2b8333315.png)

**Comment by rsilivestr** [comment]
>Появилась ошибка ts'a, нужно поправить

8164705
