### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD4thTask#6]
У меня тесты судя по всему просто зависают на этапе e2e
![image](https://user-images.githubusercontent.com/46089168/101933558-6dc75500-3bed-11eb-80c6-f56d87435c64.png)

**Comment by Fr0stmourne** [comment]
Или для запуска тестов обязательно этот адрес локалхоста открывать? Если да, то нужно сделать возможность просто прогнать обычные юнит-тесты из консоли

**Comment by rsilivestr** [comment]
> У меня тесты судя по всему просто зависают на этапе e2e
>Или для запуска тестов обязательно этот адрес локалхоста открывать? Если да, то нужно сделать возможность просто прогнать обычные юнит-тесты из консоли

Ничего открывать не надо, тесты и отчет - все в консоли.

![image](https://user-images.githubusercontent.com/31914503/101960187-ee9b4680-3c17-11eb-81e1-f5018cffb2f6.png)

Зависает потому, что FirefoxHeadless не запускается. Firefox в системе не установлен?

Заменил на jsdom, теперь будет работать:

![image](https://user-images.githubusercontent.com/31914503/101960149-d6c3c280-3c17-11eb-9337-d25a192f16c0.png)

**Comment by Fr0stmourne** [comment]
В том и дело, что ff установлен. Сейчас тесты проходят, но если приостановить сборку и прогнать их, то появляется вот эта ошибка, хотя после нее вроде бы всё равно тесты прогоняются, так и должно быть?
![image](https://user-images.githubusercontent.com/46089168/102794301-3fe7ca80-43bc-11eb-858c-fd1ecf4d6104.png)

**Comment by rsilivestr** [comment]
>В том и дело, что ff установлен. Сейчас тесты проходят, но если приостановить сборку и прогнать их, то появляется вот эта ошибка, хотя после нее вроде бы всё равно тесты прогоняются, так и должно быть?

Да, все правильно. Я тестирую уже собранный плагин. Надо компилировать в процессе запуска тестов?

**Comment by Fr0stmourne** [comment]
> > В том и дело, что ff установлен. Сейчас тесты проходят, но если приостановить сборку и прогнать их, то появляется вот эта ошибка, хотя после нее вроде бы всё равно тесты прогоняются, так и должно быть?
> 
> Да, все правильно. Я тестирую уже собранный плагин. Надо компилировать в процессе запуска тестов?

В сборке прогоняются e2e-тесты, а для юнит-тестов же не надо ничего собирать, они должны по идее независимо от сборки работать

**Comment by rsilivestr** [comment]
>В сборке прогоняются e2e-тесты, а для юнит-тестов же не надо ничего собирать

Понятно. Переделаю когда разберусь с архитектурой.
