### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD4thTask#7]
Нужно вынести все приватные методы после публичных в конец файла

**Comment by rsilivestr** [comment]
> Нужно вынести все приватные методы после публичных в конец файла

2dada352f6d5481e9c3d68c4924ef0e917687380

**Comment by Fr0stmourne** [comment]
Неочевидно, как такие методы использовать, лучше разнести на 2 метода для установки и получения значения
![image](https://user-images.githubusercontent.com/46089168/104156859-01619080-53fb-11eb-878b-3bb4673176d5.png)

**Comment by rsilivestr** [comment]
>Неочевидно, как такие методы использовать

cee6144, 708303d

**Comment by Fr0stmourne** [comment]
Нужно вынести сами функции-обработчики в отдельные методы
https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.13

![image](https://user-images.githubusercontent.com/46089168/104477659-6de2b800-55d2-11eb-8253-081b01409251.png)

**Comment by rsilivestr** [comment]
>вынести сами функции-обработчики в отдельные методы

ff580424
