### ISSUE TITLE
View

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD4thTask#8]
Не совсем понял, зачем нужно во вью валидировать значения? Это задача модели, лучше делать это там
![image](https://user-images.githubusercontent.com/46089168/103307409-000a8e00-4a21-11eb-99b6-232c224418db.png)

**Comment by rsilivestr** [comment]
> Не совсем понял, зачем нужно во вью валидировать значения? Это задача модели, лучше делать это там

2dada352f6d5481e9c3d68c4924ef0e917687380
