### ISSUE TITLE
Функциональность

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD4thTask#9]
- Нужно на все кликабельные элементы повесить `cursor: pointer`
- При клике на трек ближайший ползунок должен перемещаться в эту точку. Если будет желание, то было бы здорово сделать следующее: если нажать на трек и не отжимать, то ползунок переместится и сразу его можно будет перетаскивать (то есть без повторного нажатия). Повторюсь, это по желанию, но перемещение по клику нужно добавить

**Comment by rsilivestr** [comment]
>Нужно на все кликабельные элементы повесить cursor: pointer

208479c

>При клике на трек ближайший ползунок должен перемещаться в эту точку

7a915fc

**Comment by Fr0stmourne** [comment]
В ползунке нужно по центру подровнять текстовое значение
![image](https://user-images.githubusercontent.com/46089168/104325225-70251380-54f9-11eb-9e67-9659e1b9f4f5.png)

**Comment by rsilivestr** [comment]
>В ползунке нужно по центру подровнять текстовое значение

7061958

**Comment by Fr0stmourne** [comment]
Нужно учитывать смещение той точки, за которую передвигается ползунок, чтобы не было скачка к центру. Лучше всего это видно, если двигать за тултип
![](https://i.imgur.com/2s0utwv.gif)

**Comment by rsilivestr** [comment]
4c210aa2ebfbd3232e88808b6cdb126815216a56
